# Generated by Django 5.0 on 2023-12-10 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=50)),
                ('provincia', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=50)),
                ('telefonoContacto', models.CharField(max_length=9)),
            ],
        ),
    ]
