# Generated by Django 5.0 on 2023-12-10 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionTienda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=4)),
                ('precioVenta', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cantidad', models.IntegerField(verbose_name=4)),
                ('tiendaRelacionada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestionTienda.tienda')),
            ],
        ),
    ]
