# Generated by Django 5.0 on 2023-12-10 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionTienda', '0002_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='tienda',
            name='fechaCreacion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
